name: 'Flutter CI'
on:
  push:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:

      - name: 'Clone repository'
        uses: actions/checkout@v3


      - name: 'Set up Flutter'
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.7.3

      - run: cd 'flutter_app'
      - run: cd flutter_app && flutter pub get
      - run: cd flutter_app && flutter build apk --split-per-abi
      - run: ls flutter_app/build/app/outputs/apk/release/*.apk
      - name: "Push to releases"
        uses: ncipollo/release-action@v1
        with: 
          artifacts: flutter_app/build/app/outputs/apk/release/*.apk
          tag: v0.0.${{ github.run_number }}-aplha
          token: ${{ secrets.RELEASE_TOKEN }}
          
  build_ios: 
    runs-on: macos-latest
    permissions:
      contents: read 
    steps:
      - uses: actions/checkout@v3

      - name: 'Set up Xcode'
        uses: actions/checkout@v3 
        with:
          repository: 'apple/developer-tools'
          path: '/usr/local/tools'
          ref: 'main'

      - name: 'Install Dependencies (iOS)'
        run: cd expense_tracker && flutter pub get

      - name: 'Build iOS App'
        run: cd expense_tracker && flutter build ios 

      - name: "Upload iOS Artifact (Optional)"
        uses: actions/upload-artifact@v3 
        with:
          name: ios-app 
          path: expense_tracker/build/ios/archive 