name: 'Flutter CI'
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: 'Clone repository'
        uses: actions/checkout@v3


      - name: 'Set up Flutter'
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.7.3

      - run: ls
      - run: cd 'flutter_app'
      - run: ls
      - run: cd flutter_app && flutter pub get
      - run: ls
      - run: cd flutter_app && flutter test
      - run: ls
      - run: cd flutter_app && flutter build apk --split-per-abi
      - run: ls
      - name: "Push to releases"
        uses: ncipollo/release-action@v1
        with: 
          artifacts: '/flutter_app/build/app/outputs/release/*.apk'
          tag: v0.0.${{ github.run_number }}
          token: ${{ secrets.RELEASE_TOKEN }}