name: "TEST CI"
on:
  push:
    branches:
      - test

jobs:
  build-info:
    runs-on: ubuntu-latest
    outputs:
      app-version: ${{ steps.get_version.outputs.app_version }}
    env:
      FLUTTER_ROOT: flutter_app

    steps:
      - name: "Clone repository"
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: "Checkout workflows repo"
        uses: actions/checkout@v4
        with:
          repository: sunnydodti/workflows
          token: ${{ secrets.BUILD_INFO_TOKEN }}
          path: workflows
          ref: main
      - run: tree
      - name: "Get App Version"
        id: get_version
        run: |
          chmod +x workflows/scripts/android/get-app-version.sh
          'workflows/scripts/android/get-app-version.sh ${{ vars.FLUTTER_ROOT }}'
          echo "app_version=${{ vars.APP_VERSION }}" >> $GITHUB_OUTPUT

  build-android:
    if: ${{ github.ref_name == 'test' }}
    needs: build-info
    runs-on: ubuntu-latest
    env:
      FLAVOUR: dev
      MAIN_FILE: main-dev.dert
      FLUTTER_ROOT: flutter_app

    steps:
      - name: "Clone repository"
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: "Checkout workflows repo"
        uses: actions/checkout@v4
        with:
          repository: sunnydodti/workflows
          token: ${{ secrets.BUILD_INFO_TOKEN }}
          path: workflows
          ref: main

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "temurin"
      - run: tree
      - name: "setup android sdk"
        run: |
          chmod +x workflows/scripts/android/setup-android-sdk.sh
          workflows/scripts/android/setup-android-sdk.sh

      - name: "decode keystore"
        run: |
          chmod +x workflows/scripts/decode-keystore.sh
          workflows/scripts/decode-keystore.sh

      - run: tree

      - name: "build apk"
        run: |
          chmod +x workflows/scripts/android/build-apk.sh
          'workflows/scripts/android/build-apk.sh "${{ vars.FLUTTER_ROOT }}" "${{ vars.FLAVOUR }}" "${{vars.MAIN_FILE}}"'

      - name: "sign apk"
        run: |
          chmod +x workflows/scripts/android/sign-apk.sh
          'workflows/scripts/android/sign-apk.sh "${{ vars.FLUTTER_ROOT }}" "-${{ vars.FLAVOUR }}"'

      - name: "rename apk"
        run: |
          chmod +x workflows/scripts/android/rename-apk.sh
          'workflows/scripts/android/rename-apk.sh "${{ vars.FLUTTER_ROOT }}" "-${{ vars.FLAVOUR }}" "${{ needs.build-info.outputs.app-version }}"'
