name: "TEST CI"
on:
  push:
    branches:
      - test

jobs:
  build-info:
    runs-on: ubuntu-latest
    steps:
      - name: "Clone repository"
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: "Checkout build-info repo"
        uses: actions/checkout@v4
        with:
          repository: sunnydodti/build-info
          token: ${{ secrets.BUILD_INFO_TOKEN }}
          path: build-info
          ref: main

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "temurin"

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > keystore.jks

      - name: Tree
        run: |
          tree

      - name: "Check Keytool"
        id: check-keytol
        run: |
          keytool -h
      
      - name: "create android sdk dir"
        run: |
          mkdir -p android/sdk
          wget --output-document=android-sdk.zip --quiet 


      - run: "cd android/sdk && wget --output-document=android-sdk.zip --quiet https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip"
      - run: "cd android/sdk && unzip android-sdk.zip && rm -f android-sdk.zip"
      - run: "tree"
      - run: "yes | android/sdk/cmdline-tools/bin/sdkmanager --licenses"




